//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NavigationInterfaces
{
    [Serializable]
    public class NavigationResponse : Message
    {
        public const string k_RosMessageName = "navigation_interfaces/Navigation";
        public override string RosMessageName => k_RosMessageName;

        public float torque;
        public float steering;

        public NavigationResponse()
        {
            this.torque = 0.0f;
            this.steering = 0.0f;
        }

        public NavigationResponse(float torque, float steering)
        {
            this.torque = torque;
            this.steering = steering;
        }

        public static NavigationResponse Deserialize(MessageDeserializer deserializer) => new NavigationResponse(deserializer);

        private NavigationResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.torque);
            deserializer.Read(out this.steering);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.torque);
            serializer.Write(this.steering);
        }

        public override string ToString()
        {
            return "NavigationResponse: " +
            "\ntorque: " + torque.ToString() +
            "\nsteering: " + steering.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
