//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NavigationInterfaces
{
    [Serializable]
    public class NavigationRequest : Message
    {
        public const string k_RosMessageName = "navigation_interfaces/Navigation";
        public override string RosMessageName => k_RosMessageName;

        public float angle;
        public float speed;
        public float distance;
        public float[] front_lidar;
        public float[] rear_lidar;

        public NavigationRequest()
        {
            this.angle = 0.0f;
            this.speed = 0.0f;
            this.distance = 0.0f;
            this.front_lidar = new float[4];
            this.rear_lidar = new float[4];
        }

        public NavigationRequest(float angle, float speed, float distance, float[] front_lidar, float[] rear_lidar)
        {
            this.angle = angle;
            this.speed = speed;
            this.distance = distance;
            this.front_lidar = front_lidar;
            this.rear_lidar = rear_lidar;
        }

        public static NavigationRequest Deserialize(MessageDeserializer deserializer) => new NavigationRequest(deserializer);

        private NavigationRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angle);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.distance);
            deserializer.Read(out this.front_lidar, sizeof(float), 4);
            deserializer.Read(out this.rear_lidar, sizeof(float), 4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angle);
            serializer.Write(this.speed);
            serializer.Write(this.distance);
            serializer.Write(this.front_lidar);
            serializer.Write(this.rear_lidar);
        }

        public override string ToString()
        {
            return "NavigationRequest: " +
            "\nangle: " + angle.ToString() +
            "\nspeed: " + speed.ToString() +
            "\ndistance: " + distance.ToString() +
            "\nfront_lidar: " + System.String.Join(", ", front_lidar.ToList()) +
            "\nrear_lidar: " + System.String.Join(", ", rear_lidar.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
